version: 3.0.0
services:
  bun-remix:
    image: node:20-bookworm
    working_dir: /my-remix-app
    ports:
      - "3003:3000"
      - "3001:3001"
    env_file:
      - .env
    volumes:
      - ./my-remix-app:/my-remix-app
    # command: |
    #   # sh -c "npm install -g bun && bunx prisma db push && bun run dev"
    command: |
      sh -c "npm install -g bun && bunx prisma db push && sleep infinity"
    depends_on: [postgresql]
  postgresql:
    container_name: postgres
    image: postgres:16
    ports:
      - 5442:5432
    restart: always
    env_file:
      - .env
    hostname: postgres
    user: root